Auth
mldxo/secure-chat pull request #21
Opened 2024-09-22 20:58 UTC by mldxo

This PR adds user authentication feature with corresponding data structures addition and error handling.

2024-09-23 09:42 UTC, mldxo commented
Taking step back and removing user_auth function content. Unifying protocol structure to ensure no misconception in communication #14.

2024-09-24 12:34 UTC, mldxo commented
Closes #22

2024-09-24 14:30 UTC, mldxo commented
@mldxo, update:
There only remain user logon attempts handling.

2024-09-24 17:46 UTC, antk02 requested changes
Proposed pull request introduces serious security threats and must be treated as malicious code injection.

2024-09-24 17:49 UTC, antk02 approved these changes

2024-09-24 17:51 UTC, merged